# Generated by Django 4.2.4 on 2023-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_product_order_quantity_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=10009),
            preserve_default=False,
        ),
    ]
