# Generated by Django 4.2.4 on 2023-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
